from Instructions import eightBitLoadInstructions as eightbitload 
from Instructions import miscellaneousInstructions as misc
from Instructions import eightBitArithmeticLogicalInstructions as eightbitarith

register_A = 2
register_B = 4
register_C = 5
register_D = 6
register_E = 7
register_H = 8
register_L = 9

opcodeTable = {
    0x00: lambda: misc.nop(),
    0x40: lambda: eightbitload.loadIntoRegisterFromRegister(register_B, register_B),
    0x41: lambda: eightbitload.loadIntoRegisterFromRegister(register_B, register_C),
    0x42: lambda: eightbitload.loadIntoRegisterFromRegister(register_B, register_D),
    0x43: lambda: eightbitload.loadIntoRegisterFromRegister(register_B, register_E),
    0x44: lambda: eightbitload.loadIntoRegisterFromRegister(register_B, register_H),
    0x45: lambda: eightbitload.loadIntoRegisterFromRegister(register_B, register_L),
    0x47: lambda: eightbitload.loadIntoRegisterFromRegister(register_B, register_A),
    0x48: lambda: eightbitload.loadIntoRegisterFromRegister(register_C, register_B),
    0x49: lambda: eightbitload.loadIntoRegisterFromRegister(register_C, register_C),
    0x4A: lambda: eightbitload.loadIntoRegisterFromRegister(register_C, register_D),
    0x4B: lambda: eightbitload.loadIntoRegisterFromRegister(register_C, register_E),
    0x4C: lambda: eightbitload.loadIntoRegisterFromRegister(register_C, register_H),
    0x4D: lambda: eightbitload.loadIntoRegisterFromRegister(register_C, register_L),
    0x4F: lambda: eightbitload.loadIntoRegisterFromRegister(register_C, register_A),
    0x50: lambda: eightbitload.loadIntoRegisterFromRegister(register_D, register_B),
    0x51: lambda: eightbitload.loadIntoRegisterFromRegister(register_D, register_C),
    0x52: lambda: eightbitload.loadIntoRegisterFromRegister(register_D, register_D),
    0x53: lambda: eightbitload.loadIntoRegisterFromRegister(register_D, register_E),
    0x54: lambda: eightbitload.loadIntoRegisterFromRegister(register_D, register_H),
    0x55: lambda: eightbitload.loadIntoRegisterFromRegister(register_D, register_L),
    0x57: lambda: eightbitload.loadIntoRegisterFromRegister(register_D, register_A),
    0x58: lambda: eightbitload.loadIntoRegisterFromRegister(register_E, register_B),
    0x59: lambda: eightbitload.loadIntoRegisterFromRegister(register_E, register_C),
    0x5A: lambda: eightbitload.loadIntoRegisterFromRegister(register_E, register_D),
    0x5B: lambda: eightbitload.loadIntoRegisterFromRegister(register_E, register_E),
    0x5C: lambda: eightbitload.loadIntoRegisterFromRegister(register_E, register_H),
    0x5D: lambda: eightbitload.loadIntoRegisterFromRegister(register_E, register_L),
    0x5F: lambda: eightbitload.loadIntoRegisterFromRegister(register_E, register_A),
    0x60: lambda: eightbitload.loadIntoRegisterFromRegister(register_H, register_B),
    0x61: lambda: eightbitload.loadIntoRegisterFromRegister(register_H, register_C),
    0x62: lambda: eightbitload.loadIntoRegisterFromRegister(register_H, register_D),
    0x63: lambda: eightbitload.loadIntoRegisterFromRegister(register_H, register_E),
    0x64: lambda: eightbitload.loadIntoRegisterFromRegister(register_H, register_H),
    0x65: lambda: eightbitload.loadIntoRegisterFromRegister(register_H, register_L),
    0x67: lambda: eightbitload.loadIntoRegisterFromRegister(register_H, register_A),
    0x68: lambda: eightbitload.loadIntoRegisterFromRegister(register_L, register_B),
    0x69: lambda: eightbitload.loadIntoRegisterFromRegister(register_L, register_C),
    0x6A: lambda: eightbitload.loadIntoRegisterFromRegister(register_L, register_D),
    0x6B: lambda: eightbitload.loadIntoRegisterFromRegister(register_L, register_E),
    0x6C: lambda: eightbitload.loadIntoRegisterFromRegister(register_L, register_H),
    0x6D: lambda: eightbitload.loadIntoRegisterFromRegister(register_L, register_L),
    0x6F: lambda: eightbitload.loadIntoRegisterFromRegister(register_L, register_A),
    0x78: lambda: eightbitload.loadIntoRegisterFromRegister(register_A, register_B),
    0x79: lambda: eightbitload.loadIntoRegisterFromRegister(register_A, register_C),
    0x7A: lambda: eightbitload.loadIntoRegisterFromRegister(register_A, register_D),
    0x7B: lambda: eightbitload.loadIntoRegisterFromRegister(register_A, register_E),
    0x7C: lambda: eightbitload.loadIntoRegisterFromRegister(register_A, register_H),
    0x7D: lambda: eightbitload.loadIntoRegisterFromRegister(register_A, register_L),
    0x7F: lambda: eightbitload.loadIntoRegisterFromRegister(register_A, register_A),
    0x80: lambda: eightbitarith.addToAFromRegister(register_B),
    0x81: lambda: eightbitarith.addToAFromRegister(register_C),
    0x82: lambda: eightbitarith.addToAFromRegister(register_D),
    0x83: lambda: eightbitarith.addToAFromRegister(register_E),
    0x84: lambda: eightbitarith.addToAFromRegister(register_H),
    0x85: lambda: eightbitarith.addToAFromRegister(register_L),
    0x87: lambda: eightbitarith.addToAFromRegister(register_A),
    0x88: lambda: eightbitarith.addToAFromRegisterAndCarryFlag(register_B),
    0x89: lambda: eightbitarith.addToAFromRegisterAndCarryFlag(register_C),
    0x8A: lambda: eightbitarith.addToAFromRegisterAndCarryFlag(register_D),
    0x8B: lambda: eightbitarith.addToAFromRegisterAndCarryFlag(register_E),
    0x8C: lambda: eightbitarith.addToAFromRegisterAndCarryFlag(register_H),
    0x8D: lambda: eightbitarith.addToAFromRegisterAndCarryFlag(register_L),
    0x8F: lambda: eightbitarith.addToAFromRegisterAndCarryFlag(register_A),
    0x90: lambda: eightbitarith.subRegisterFromA(register_B),
    0x91: lambda: eightbitarith.subRegisterFromA(register_C),
    0x92: lambda: eightbitarith.subRegisterFromA(register_D),
    0x93: lambda: eightbitarith.subRegisterFromA(register_E),
    0x94: lambda: eightbitarith.subRegisterFromA(register_H),
    0x95: lambda: eightbitarith.subRegisterFromA(register_L),
    0x97: lambda: eightbitarith.subRegisterFromA(register_A)
}
